### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by williamjiancui** [chen0112/oiltype-prediction#2]
'Questions' from Jian, 2020-10-26
1. Are the five biomarkers Terpanes Diamantanes	MA-steranes	TA-steranes and	Steranes?
2. Are the items under each biomarker the features? such as C25/H35S, H35/H32R.
3. What are the PC1 ~ PC13 then?
4. Is 9/2 a name of feature or a fraction (9/2 = 4.5)?
5. What does a user need to input on webpage? numbers or just one or some features selected from dropdown?
6. In the index.html, you give some the features of MA-steranes in input boxes. Should all of them be transimitted to model? or just one of the feature at a time?

**Comment by chen0112** [comment]
1. Yes, these are five biomarkers.

2. Yes, items under each bio markers are features as input on the webpage

3. PC1 -PC13 don’t matter, cuz it’s from principal components analysis to
help me define which factors are important, don’t need them in code

4. 9/2 or something like this with numbers, are abbreviations of their
original biomarkers, since their original names are too long and they are
not dividing in math. They are also features
5. User needs to put in features value. For example, streanes have 7
features, users have to put in 7 different values corresponding to these 7
features. If we can have a drop down for different biomarkers and when user
choose different biomarkers, the input features will change that biomarker
corresponding features, then it will be awesome. Easier version could be
just the best biomarker‘s input out of five instead.

6. In the example of MA-streanes, all the features should be transmitted to
the model, cuz the model needs all 7 features to calculate the result.
